name: Update Contributors

on:
  workflow_dispatch:

jobs:
  contrib-readme:
    runs-on: ubuntu-latest
    name: Update contributors
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: BobAnkh/add-contributors@master
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTRIBUTOR: '## Участники'
          COLUMN_PER_ROW: '6'
          IMG_WIDTH: '100'
          AVATAR_SHAPE: 'round'     
          COMMIT_MESSAGE: 'chore: update contributors list [skip ci]'
          PATH: '/README.md'
